source 'http://rubygems.org'
gem 'sinatra'
gem 'eventmachine'
gem 'haml'
gem 'sass'
gem 'datamapper'
gem 'dm-sqlite-adapter'
gem 'dm-serializer'
gem 'json'
gem 'thin'
group :test do
  gem 'rspec', '2.7.0'
  gem 'cucumber'
  gem 'autotest'
  gem 'ZenTest'
  gem 'capybara'
  gem 'cucumber-sinatra'
end
